### PR TITLE
Add ability to modify services after registration

### PR DESCRIPTION
**Pull request by gwynne**
See commit for details. Intended usage is something like this:

```swift
extension MediaType {
    static let cooltype = MediaType(type: "application", subtype: "x-my-cool-media-type")
}

class SomeProvider: Provider {
    func register(_ services: inout Services) {
        services.supplement(ContentConfig.self) { (config: inout ContentConfig, _) in
            config.use(cooltypeEncoder, for: .cooltype)
            config.use(cooltypeDecoder, for: .cooltype)
        }
    }
}
```

Currently this can't be done in a way that's safe for more than one provider at a time, and requires knowing implementation details (specifically that the framework registers `ContentConfig.default()` by default).

I originally wanted to use "extend" for this, but there's already an `Extend` protocol that does something completely different. The verb "supplement" feels a little awkward to me, but it's the best I could think of. Any suggestions on alternatives are welcome.

### CODE REVIEW

**Comment by Joannis** [comment]
I'd love this one! I don't feel that `supplement` covers what is being done. Maybe `expand`?

**Comment by Joannis** [comment]
Or some other names:

- modify
- mutate
- overwrite
- map
- replace

**Comment by tanner0101** [comment]
This is possible currently as long as you register the service as a singleton. This is how routing works. 

However, I do like the idea of this convenience function. I think taking advantage of the singleton pattern here would allow us to implement this in a lot less code.

Perhaps the `.supplement` function could just `.make()` the type passed in, (optionally verify it's actually a singleton), pass it to the closure, then done. That would be very easy. :)

**Comment by gwynne** [comment]
Sure, but I don't think the utility of this functionality is limited to singletons - I'm sure there are use cases for configurability of many-instance services as well.

**Comment by tanner0101** [comment]
I think you could solve that problem (configurability of many-instance services) by registering a singleton object that configures them. Configure the singleton "config" object normally, then each of the many-instance services get that config when they are created.

**Comment by tanner0101** [comment]
Keeping this open until we have either a documented way to achieve this with singletons or actual API.

**Comment by tanner0101** [comment]
Current decision (still up for debate): implement this yourself using a class (singleton) service.

**Comment by penny-coin** [comment]
Hey @gwynne, you just merged a pull request, have a coin! 

You now have 254 coins.

**Pull request merged**
