### PR TITLE
Update internal variable name to match type

### PR DESCRIPTION
**Pull request by siemensikkema**

### CODE REVIEW

**Comment by calebkleveter** [comment]
I like this change, but it breaks the API. I have a few third-party services that implement the `ServiceType` protocol where I would have to fix this. I think we should wait for Service 2.0 to make this change or somehow do a deprecation (if that is possible in this case).

**Comment by siemensikkema** [comment]
@calebkleveter it's just the internal variable though so it's more like a suggestion. Xcode will use it for autocomplete but you can change it to anything you want.

**Comment by rafiki270** [comment]
I like it too and don't think there are any breaking changes there ... ?

**Review by rafiki270 — APPROVED** [review]

**Comment by calebkleveter** [comment]
Hm, didn't know that. In that case, I'm all for it!

**Review by calebkleveter — APPROVED** [review]

**Review by tanner0101 — APPROVED** [review]
Thanks :)

**Comment by penny-coin** [comment]
Hey @siemensikkema, you just merged a pull request, have a coin! 

You now have 118 coins.

**Pull request merged**
