### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by grundoon**
update chat badge to Discord

### CODE REVIEW

**Comment by 0xTim** [comment]
`vapor.team` should still redirect to Discord, at least it does for me

**Comment by grundoon** [comment]
@0xTim Quite true, but this (_these_... 4 total I think) are more about the broken badge:

screen shot 2018-10-12 at 16 11 32

(Also the current broken ones are http:// rather than https:// – I think this URL simply unwraps the redirect, and puts the burden of maintaining the cert validity on Discord and shields.io themselves.)

**Comment by 0xTim** [comment]
Badge makes sense, link I guess it up to the core team. I know @joscdk wanted the server moved to Vapor Cloud to stop the certs expiring

**Comment by penny-coin** [comment]
Hey @grundoon, you just merged a pull request, have a coin! 

You now have 95 coins.

**Comment by tanner0101** [comment]
thanks!

**Pull request merged**
